version: '3.5'

services:

### keycloak #####################################################
    keycloak:
      build:
        context: ./keycloak
        args:
          - KEYCLOAK_VERSION=${KEYCLOAK_VERSION}
      container_name: keycloak
      environment:
        - DB_ADDR=${KEYCLOAK_DB_ADDR}
        - DB_PORT=${KEYCLOAK_DB_PORT}
        - DB_DATABASE=${KEYCLOAK_DB_DATABASE}
        - DB_SCHEMA=${KEYCLOAK_DB_SCHEMA}
        - DB_USER=${KEYCLOAK_DB_USER}
        - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      networks:
          - frontend
          - backend
      ports:
        - "8088:8080"
